version: '3.3'
services:
  db:
    restart: always
    container_name: scheduler-database
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=interviewScheduler
      - MYSQL_USER=ayush
      - MYSQL_PASSWORD=password
    volumes:
      - /Users/ayush.saraf/Documents/startupscripts:/docker-entrypoint-initdb.d
      - /Users/ayush.saraf/Documents:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    restart: on-failure
    build: .
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080
